### ISSUE TITLE
Resetting the prompts per sample

### ISSUE THREAD

**Issue by HeejiWon** [azshue/TPT#16]
> Hi, thank you for your interest in our work. To answer your questions:
> 
> 1. Yes, the test image is evaluated immediately on the optimized prompt.
> 2. When a new test image comes in, the prompt will be reset to its initial state ("a photo of a" or the initial CoOp weight).
---
Hi, Thank you for your response! But I’m still curious about the reasoning behind resetting the prompts to their initial state when a new test image is introduced. Could you explain why the previous optimized prompt is not utilized for the next test image?

Originally posted by @Even-ok in https://github.com/azshue/TPT/issues/14#issuecomment-2373348281

---
Hi, thanks for your great work!
I have same question as @Even-ok.
Can you explain the reason for resetting prompts per sample?
I expected to train prompts with all samples, which is a general training method.

**Comment by azshue** [comment]
Hi @HeejiWon ,

In our experiment, we assume there is no correlation between the current test sample and the previous one (which is a fair setting in real-world cases), so it doesn't make sense to re-use the prompt optimized on an irrelevant test sample on the current one. For this reason, we haven't tried re-using previously optimized prompts on the following test sample. 

I'd guess re-using the prompt might help in academic testing settings like the ones in the paper because all test samples come from the same dataset of similar distribution. But it may also hurt the performance, because the accumulated update may cause the soft prompt to degenerate. Again, I haven't tried this back when I was working on this project. You're welcome to try it yourself and find out.

I hope this helps. Thank you.
